module.exports = {
  insertionSort: require('./build/sorting/insertion-sort').algCoffee.insertionSort,
  radixSort: require('./build/sorting/radix-sort').algCoffee.radixSort,
  mergeSort: require('./build/sorting/merge-sort').algCoffee.mergeSort,
  heapSort: require('./build/sorting/heap-sort').algCoffee.heapSort,
  bstSort: require('./build/sorting/bst-sort').algCoffee.bstSort,
  euclideanDistance: require('./build/math/euclidean-distance').algCoffee.euclideanDistance,
  karatsubaMultiplication: require('./build/math/karatsuba-multiplication').algCoffee.karatsubaMultiplication,
  knuthShuffle: require('./build/math/knuth-shuffle').algCoffee.knuthShuffle,
  nextPermutation: require('./build/math/next-permutation').algCoffee.nextPermutation,
  reservoirSampling: require('./build/math/reservoir-sampling').algCoffee.reservoirSampling,
  binarySearch: require('./build/search/binary-search').algCoffee.binarySearch,
  bellmanFord: require('./build/graph/bellman-ford').algCoffee.bellmanFord,
  depthFirstSearch: require('./build/graph/depth-first-search').algCoffee.depthFirstSearch,
  breadthFirstSearch: require('./build/graph/breadth-first-search').algCoffee.breadthFirstSearch,
  edmondsKarp: require('./build/graph/edmonds-karp').algCoffee.edmondsKarp,
  kosaraju: require('./build/graph/kosaraju').algCoffee.kosaraju,
  kruskal: require('./build/graph/kruskal').algCoffee.kruskal,
  editDistance: require('./build/string/edit-distance').algCoffee.editDistance,
  knuthMorrisPratt: require('./build/string/knuth-morris-pratt').algCoffee.knuthMorrisPratt,
  longestCommonSubsequence: require('./build/string/longest-common-subsequence').algCoffee.longestCommonSubsequence,
  karpRabin: require('./build/string/karp-rabin').algCoffee.karpRabin,
  AdjacencyList: require('./build/data-structures/adjacency-list').algCoffee.AdjacencyList,
  BinarySearchTree: require('./build/data-structures/binary-search-tree').algCoffee.BinarySearchTree,
  Heap: require('./build/data-structures/heap').algCoffee.Heap,
  DisjointSet: require('./build/data-structures/disjoint-set').algCoffee.DisjointSet,
  SegmentTree: require('./build/data-structures/segment-tree').algCoffee.SegmentTree
};
